### ISSUE TITLE
Meta information

### ISSUE THREAD

**Issue by mdeweerd** [tetienne/python-veolia-api#94]
I had some trouble finding this repository - I was looking for the same reason as #22 and [HA integration](https://github.com/tetienne/veolia-custom-component/issues/28) .
But finally the HA integration and the library are managed by the same person .

The PKG-INFO indicates that the homepage is "https://github.com/tetienne/pyolia", but that does not exist, so it would be nice to update it.

**Comment by tetienne** [comment]
You are right. Thx for reporting this. I will fix it as soon as possible. It should be quick indeed.
